### ISSUE TITLE
 how to set table's charset to utf8 by ef core?

### ISSUE THREAD

**Issue by jucheap** [Kagamine/YuukoBlog-NETCore-MySql#2]
when i use "Pomelo.EntityFrameworkCore.MySql"  in ef core,mysql table created like this:
CREATE TABLE `pathcodes` (
  `Id` varchar(20) NOT NULL,
  `Code` varchar(4) NOT NULL,
  `CreateDateTime` datetime(6) NOT NULL,
  `IsDeleted` bit(1) NOT NULL,
  `Len` int(11) NOT NULL,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT **CHARSET=latin1**

 how to set table's charset to utf8 by ef core?

**Comment by yukozh** [comment]
Add charset=utf8 into your connection string.

**Comment by jucheap** [comment]
I already added that to my connection string,but when created the database,it was still created  in character of latin1. the connection string as follows:
**Datasource=localhost;Database=mydbtest;uid=root;pwd=123456;Character Set=utf8;Allow User Variables=True**

**Comment by yukozh** [comment]
Which pomelo version are you using? could you try to use the latest version?

**Comment by jucheap** [comment]
I'm using version 1.1.0.
