### ISSUE TITLE
因为用了IdentityUser才报错，不用就正常

### ISSUE THREAD

**Issue by qibucloud** [Kagamine/YuukoBlog-NETCore-MySql#3]
因为用了IdentityUser才报错，不用就正常,是我那里没有设置好吗？

An error occurred while starting the application.
MySqlException: Index column size too large. The maximum column size is 767 bytes.
MySql.Data.MySqlClient.MySqlDataReader.ActivateResultSet(ResultSet resultSet)
MySqlException: Index column size too large. The maximum column size is 767 bytes.

Qibu.Startup.InitializeQibuCoreDatabase(IServiceProvider serviceProvider) in Startup.cs
+
                if (db.Database.EnsureCreated())
Qibu.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory) in Startup.cs
+
            InitializeQibuCoreDatabase(app.ApplicationServices);

**Comment by yukozh** [comment]
This is an upstream issue, please move it into https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql
